### ISSUE TITLE
Add DSTT

### ISSUE THREAD

**Issue by Invictaz** [DS-Homebrew/flashcard-archive#6]
Please add DSTT stuff

Example sources

http://jeuxkiff.canalblog.com/archives/2012/10/17/25354677.html

https://www.linfoxdomain.com/nintendo/ds/

**Comment by lifehackerhansol** [comment]
I have a bit of an issue with this.

I cannot add YSMenu, which is _absolutely_ what you should be using, because the license disallows me to.

I would then have to add the official TTMenu, which has an anti-fake built in.

I would then have to include both a DSTTFlashWriter for those who use it, and the flash backup. Which is just confusing in the long run for people who just need to get things going.

The best I can do is add a note that you must use YSMenu from the YSMenu download page. Or at least documentation. I don't want people to accidentally brick their flashcart when it's rather unnecessary for them to. 

I'm simply unsure what is the best way to not brick carts. All kernels here don't actually have a fake-brick built in, but the official DSTT kernel does.

**Comment by Invictaz** [comment]
You can host older than 1.16 kernels that don't have the fake killer inside them.

My request was for preservation of the DSTT cart related files. The files are becoming scarce. Plus the flash backup dumps are very usefull to recover a cart in case of ntrboothax flashed carts.

**Comment by lifehackerhansol** [comment]
Actually, doesn't RetroGameFan also have TTMenu? Is there a reason to archive the official version if RGF has a better, updated one developed alongside YSMenu?

**Comment by lifehackerhansol** [comment]
After some thought I think I am going to leave the DSTT stuff as is for now. A fully functional and updated TTMenu exists in RetroGameFan's download, the same one as YSMenu. So I don't think this is necessary.

**Comment by Invictaz** [comment]
The problem with RGF is that it's not on Github but a private forum, which is subdue to vanish. Having it all close to the chest on Github, in a one stop shop location is preferred.

**Comment by lifehackerhansol** [comment]
And I cannot host it here because of RetroGameFan's license. So long as it is still up on GBAtemp I won't be able to put it up anywhere else.

**Comment by Invictaz** [comment]
You can host the original DSTT files. I even gave you a site where they are now 

https://github.com/DS-Homebrew/flashcard-archive/issues/6#issue-1060634140

**Comment by lifehackerhansol** [comment]
I am aware I can do so, and I would rather direct people to get the latest version of their stuff rather than an outdated version. 
Hell, I personally think this entire YSMenu folder *shouldn't exist*, because someone who is going to find it will think that is the latest version and use it which isn't the goal of this archive at all. This has already happened once: #4.
I kept it anyway because the kernels in the YSMenu folders aren't straight up YSMenu or TTMenu, it has other components like a main menu and other things specific to the cart itself. A cart that comes directly with only TTMenu or YSMenu don't have anything unique or requiring archives when RetroGameFan has one right there on GBATemp.

**Comment by Invictaz** [comment]
For completeness sake my cart came with an older version of the TTMenu and did not have YSMenu at all. So I would opt for more files the better. And yes, a readme file to show what is what. Newer is not always better as it comes to DSTT.
