### ISSUE TITLE
ge.ndsi.in GEi HOT kernel

### ISSUE THREAD

**Issue by lifehackerhansol** [DS-Homebrew/flashcard-archive#7]
Missing. Not found on Wayback Machine, GBAtemp or FileTrip. 

If anyone has this cart, or has the kernel, please create a pull request or upload here.

**Comment by heydootdoot** [comment]
hello @lifehackerhansol, i don't have the kernel for this sadly but i'm here to upload the dumps of this flashcard since it's hard to come by and i happen to fortunately acquire it so why not have it uploaded so we can learn about it further than having nothing at all regarding this GEi HOT flashcard.

i also have tagged you on Discord but i think discussing it here would be better since my message wouldn't be stacked by other messages and people can look it up easily on the internet or maybe engage in this discussion if someone happens to found this kernel (hopefully).
but if you want to talk about it on Discord then i would.

one thing i know about this flashcard though is that it functions like normal GEi flashcard, it wouldn't show anything if there's no microSD inserted with files in it, but when i put my normal GEi microSD with it's kernel to GEi HOT, it shows this error screen "Can't open _dsmenu.dat" so i guess it's trying to detect the present of that file first.
![Screenshot 2023-11-04 18-36-15](https://github.com/DS-Homebrew/flashcard-archive/assets/69449548/3207dc2c-efc5-4e44-b87b-ac6e916067e6)

here are pictures of it's PCB:
![IMG_20230813_232055](https://github.com/DS-Homebrew/flashcard-archive/assets/69449548/0c061fed-feaa-4c19-b957-342c7486b76d)
![IMG_20230813_232201](https://github.com/DS-Homebrew/flashcard-archive/assets/69449548/e0a0d1a7-7341-4869-85be-a5bb6afe5d01)
![IMG_20230813_232513](https://github.com/DS-Homebrew/flashcard-archive/assets/69449548/d08b6118-45ea-4f87-b33a-0ce46a636c8d)
![IMG_20230813_232811](https://github.com/DS-Homebrew/flashcard-archive/assets/69449548/a9509e4e-f024-4900-9cfc-7a2acf3f8a5f)
![IMG_20230813_232908](https://github.com/DS-Homebrew/flashcard-archive/assets/69449548/9c39e907-442b-4d5f-9c06-8f0e2080acd4)
![IMG_20230813_232941](https://github.com/DS-Homebrew/flashcard-archive/assets/69449548/92c9612f-0a09-47dc-abd5-5ba73280e6f5)
![IMG_20230813_233233](https://github.com/DS-Homebrew/flashcard-archive/assets/69449548/5dc640e6-d2d9-4e53-8788-578e22c24d64)
![IMG_20230813_233356](https://github.com/DS-Homebrew/flashcard-archive/assets/69449548/df2abf20-91be-4817-aedf-dec4c1a224a2)
![IMG_20230813_233837](https://github.com/DS-Homebrew/flashcard-archive/assets/69449548/2dffdc1e-6e87-45ab-b30a-116a94bdfceb)

and here's the dump:
https://mega.nz/file/tuBinCIB#TIPWu9jjBSz_-69CUGC2F3etAMiFhQApGAgb5iQtNdU

if it againts the rule to upload these dumps then i will delete it, but i would still keep the files for preservation sake.

that's all i have regarding GEi HOT flashcard at the moment, it's sad to see that kernels from the official website www.ge.ndsi.in haven't been archived and i can't promise to found GEi HOT kernel somday, but i hope this dump could shed some light about this flashcard and help people who happen to have this flashcad too.
maybe also help this guy on reddit because it's been 2+ year https://www.reddit.com/r/nds/comments/mztyeq/i_found_a_nds_xl_on_my_garage_how_do_i_fix_it/

**Comment by lifehackerhansol** [comment]
Blind shot, wanna see if the Ace3DS+ kernel or the Gateway Blue kernel works?

I feel like it's one of the two

**Comment by heydootdoot** [comment]
> Blind shot, wanna see if the Ace3DS+ kernel or the Gateway Blue kernel works?
> 
> I feel like it's one of the two

i could try but i'm scared that it would bricked the card, the reason is because i used to have another GEi flashcard (normal one) that somehow got bricked when i launch it from unlaunch on my DSi and i ended up have to buy a new one.

if it's not something that would end up what like that when testing it on this flashcard then yeah i could try

**Comment by heydootdoot** [comment]
is it this https://flashcard-archive.ds-homebrew.com/Ace3DS+_R4iLS/ and this https://flashcard-archive.ds-homebrew.com/Gateway_Blue/? if so, i'll update my comment once i tried it

**Comment by heydootdoot** [comment]
i have news, https://flashcard-archive.ds-homebrew.com/Ace3DS+_R4iLS/ kernel works with GEi HOT!! and it also able to play games with nds-bootstrap through TWLMenu or Ace3DS+ own kernel. as for https://flashcard-archive.ds-homebrew.com/Gateway_Blue/ kernel, somehow it results in the same "Can't open _dsmenu.dat" error screen.

here's a video of me using Ace3DS+ kernel on GEi HOT flashcard, first time booting it will blast you with level 4 brightness and i don't know how to decrease it.
i'm sorry if it's blurry, dark and the colour gradients looking bad, i don't know what went wrong when i install DS TV Out mod with just 8 resistors. also i have to shorten the video because i can only upload video under 10mb.
https://github.com/DS-Homebrew/flashcard-archive/assets/69449548/c57c3245-09de-4103-bc11-c39101d3df23

anyway, it's confirmed now that GEi HOT is compatible with Ace3DS+ kernel, i hope that guy on reddit can finally use that card.
